#pragma once

#include <driver/gpio.h>
#include <driver/i2c_master.h>
#include <driver/spi_master.h>

// I2cMasterBus takes (scl, sda, port), so keep these two names explicit.
#define C6_AMOLED_I2C_SCL_NUM 7
#define C6_AMOLED_I2C_SDA_NUM 8
#define C6_AMOLED_I2C_SCL GPIO_NUM_7
#define C6_AMOLED_I2C_SDA GPIO_NUM_8
#define C6_AMOLED_I2C_PORT I2C_NUM_0
#define C6_AMOLED_PMIC_ADDRESS 0x34

#define C6_AMOLED_LCD_SPI_HOST SPI2_HOST
#define C6_AMOLED_LCD_H_RES 480
#define C6_AMOLED_LCD_V_RES 480
#define C6_AMOLED_LCD_PCLK GPIO_NUM_0
#define C6_AMOLED_LCD_DATA0 GPIO_NUM_1
#define C6_AMOLED_LCD_DATA1 GPIO_NUM_2
#define C6_AMOLED_LCD_DATA2 GPIO_NUM_3
#define C6_AMOLED_LCD_DATA3 GPIO_NUM_4
#define C6_AMOLED_LCD_CS GPIO_NUM_15

#define C6_AMOLED_TOUCH_RST GPIO_NUM_11
#define C6_AMOLED_TOUCH_INT GPIO_NUM_5

#define C6_AMOLED_I2S_MCLK_NUM 19
#define C6_AMOLED_I2S_BCLK_NUM 20
#define C6_AMOLED_I2S_LRCK_NUM 22
#define C6_AMOLED_I2S_DOUT_NUM 23
#define C6_AMOLED_I2S_DIN_NUM 21
#define C6_AMOLED_I2S_MCLK GPIO_NUM_19
#define C6_AMOLED_I2S_BCLK GPIO_NUM_20
#define C6_AMOLED_I2S_LRCK GPIO_NUM_22
#define C6_AMOLED_I2S_DOUT GPIO_NUM_23
#define C6_AMOLED_I2S_DIN GPIO_NUM_21

#define C6_AMOLED_SD_CLK GPIO_NUM_0
#define C6_AMOLED_SD_MOSI GPIO_NUM_1
#define C6_AMOLED_SD_MISO GPIO_NUM_2
#define C6_AMOLED_SD_CS GPIO_NUM_6
