// Bakes anti-aliased glyph coverage maps at build time.
//
// The firmware has no allocator and no room for a runtime rasterizer, but the
// UI still needs genuinely high-quality text: crisp at 480x480, and large
// enough to read at arm's length. So each size we actually use is rasterized
// here, on the host, straight from the TTF outlines into 8-bit coverage - the
// same thing a desktop rasterizer produces - and the firmware only has to
// alpha-blend it. No runtime scaling anywhere, which is what would otherwise
// make embedded text look soft or chunky.
//
// Coverage bytes go to raw .bin files in OUT_DIR (include_bytes! keeps compile
// times sane - a 100 KB Rust array literal does not), and the small per-glyph
// metadata table is emitted as generated Rust alongside it.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

const DIGITS: &str = "0123456789:";
const UPPER: &str = "ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ";
// Relay names come from the irrigation controller's config and are arbitrary
// Swedish free text, so the body sizes need the full latin set plus åäö.
const BODY: &str = "\
 !\"#%&'()*+,-./0123456789:;<=>?@\
ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_\
abcdefghijklmnopqrstuvwxyz{|}~\
ÅÄÖåäöéÉ·°";

struct FontSpec {
    ident: &'static str,
    ttf: &'static str,
    px: f32,
    charset: &'static str,
}

// Only the sizes the UI actually draws, each with the narrowest charset that
// covers its job - the countdown never renders a letter, so it does not pay
// for one.
const FONTS: &[FontSpec] = &[
    // Hero countdown digits.
    FontSpec { ident: "COUNTDOWN", ttf: "Barlow-Bold.ttf", px: 176.0, charset: DIGITS },
    // Clock, and the big in-button words (GO!, CANCEL).
    FontSpec { ident: "DISPLAY", ttf: "Barlow-Bold.ttf", px: 76.0, charset: "0123456789:!ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ " },
    // Menu labels and relay names.
    FontSpec { ident: "BODY", ttf: "Barlow-SemiBold.ttf", px: 40.0, charset: BODY },
    // Captions: units, secondary schedule lines.
    FontSpec { ident: "CAPTION", ttf: "Barlow-SemiBold.ttf", px: 27.0, charset: BODY },
];

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets = manifest.join("assets");

    println!("cargo:rerun-if-changed=build.rs");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit.\n");

    for spec in FONTS {
        let path = assets.join(spec.ttf);
        println!("cargo:rerun-if-changed={}", path.display());
        let data = fs::read(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        let face = fontdue::Font::from_bytes(data, fontdue::FontSettings::default())
            .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));

        let mut bitmap: Vec<u8> = Vec::new();
        let mut entries = String::new();
        let mut count = 0usize;

        // Sorted and deduplicated so the firmware can binary-search by char.
        let mut chars: Vec<char> = spec.charset.chars().collect();
        chars.sort_unstable();
        chars.dedup();

        for ch in chars {
            let (metrics, coverage) = face.rasterize(ch, spec.px);
            let offset = bitmap.len();
            bitmap.extend_from_slice(&coverage);
            // fontdue gives ymin as the baseline-relative bottom edge, positive
            // upward. The blitter wants a downward top edge, so flip it here
            // rather than in the hot path.
            let top = -(metrics.ymin + metrics.height as i32);
            writeln!(
                generated_entry(&mut entries),
                "    Glyph {{ ch: '{}', w: {}, h: {}, left: {}, top: {}, advance: {}, offset: {} }},",
                escape(ch),
                metrics.width,
                metrics.height,
                metrics.xmin,
                top,
                metrics.advance_width.round() as i32,
                offset,
            )
            .unwrap();
            count += 1;
        }

        let bin_name = format!("font_{}.bin", spec.ident.to_lowercase());
        fs::write(out_dir.join(&bin_name), &bitmap).unwrap();

        let line_metrics = face
            .horizontal_line_metrics(spec.px)
            .expect("font has no horizontal line metrics");

        writeln!(
            generated,
            "pub static {ident}: Font = Font {{\n    \
                 glyphs: &[\n{entries}    ],\n    \
                 coverage: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{bin}\")),\n    \
                 ascent: {ascent},\n    \
                 line_height: {line},\n    \
                 px: {px},\n}};\n",
            ident = spec.ident,
            entries = entries,
            bin = bin_name,
            ascent = line_metrics.ascent.round() as i32,
            line = (line_metrics.ascent - line_metrics.descent + line_metrics.line_gap).round() as i32,
            px = spec.px.round() as i32,
        )
        .unwrap();

        println!(
            "cargo:warning={} px={} glyphs={} coverage={} KiB",
            spec.ident,
            spec.px,
            count,
            bitmap.len() / 1024
        );
    }

    fs::write(out_dir.join("fonts.rs"), generated).unwrap();
}

// Tiny shim so the writeln! above can borrow the entries buffer inline.
fn generated_entry(s: &mut String) -> &mut String {
    s
}

fn escape(ch: char) -> String {
    match ch {
        '\'' => "\\'".to_string(),
        '\\' => "\\\\".to_string(),
        c => c.to_string(),
    }
}
