// Bakes anti-aliased glyph coverage maps at build time.
//
// The firmware has no allocator and no room for a runtime rasterizer, but the
// UI still needs genuinely high-quality text: crisp at 480x480, and large
// enough to read at arm's length. So each size we actually use is rasterized
// here, on the host, straight from the TTF outlines into 8-bit coverage - the
// same thing a desktop rasterizer produces - and the firmware only has to
// alpha-blend it. No runtime scaling anywhere, which is what would otherwise
// make embedded text look soft or chunky.
//
// Coverage bytes go to raw .bin files in OUT_DIR (include_bytes! keeps compile
// times sane - a 100 KB Rust array literal does not), and the small per-glyph
// metadata table is emitted as generated Rust alongside it.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const DIGITS: &str = "0123456789:";
const MICRO_CHARS: &str = "0123456789:%";
// Relay names come from the irrigation controller's config and are arbitrary
// Swedish free text, so the body sizes need the full latin set plus åäö.
const BODY: &str = "\
 !\"#%&'()*+,-./0123456789:;<=>?@\
ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_\
abcdefghijklmnopqrstuvwxyz{|}~\
ÅÄÖåäöéÉ·°";

struct FontSpec {
    ident: &'static str,
    ttf: &'static str,
    px: f32,
    charset: &'static str,
}

// Only the sizes the UI actually draws, each with the narrowest charset that
// covers its job - the countdown never renders a letter, so it does not pay
// for one.
const FONTS: &[FontSpec] = &[
    // Compact persistent timer badge.
    FontSpec {
        ident: "MICRO",
        ttf: "Barlow-SemiBold.ttf",
        px: 20.0,
        charset: MICRO_CHARS,
    },
    // Hero countdown digits.
    // Sized so "12:34" fits inside the countdown ring's inner radius with room
    // to spare, while staying the largest type on the device.
    FontSpec {
        ident: "COUNTDOWN",
        ttf: "Barlow-Bold.ttf",
        px: 146.0,
        charset: DIGITS,
    },
    // Clock, and the big in-button words (GO!, CANCEL).
    FontSpec {
        ident: "DISPLAY",
        ttf: "Barlow-Bold.ttf",
        px: 76.0,
        charset: "0123456789:!ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ ",
    },
    // Menu labels and relay names.
    FontSpec {
        ident: "BODY",
        ttf: "Barlow-SemiBold.ttf",
        px: 40.0,
        charset: BODY,
    },
    // Captions: units, secondary schedule lines.
    FontSpec {
        ident: "CAPTION",
        ttf: "Barlow-SemiBold.ttf",
        px: 27.0,
        charset: BODY,
    },
];

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets = manifest.join("assets");

    println!("cargo:rerun-if-changed=build.rs");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit.\n");

    for spec in FONTS {
        let path = assets.join(spec.ttf);
        println!("cargo:rerun-if-changed={}", path.display());
        let data =
            fs::read(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        let face = fontdue::Font::from_bytes(data, fontdue::FontSettings::default())
            .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));

        let mut bitmap: Vec<u8> = Vec::new();
        let mut entries = String::new();
        let mut count = 0usize;

        // Sorted and deduplicated so the firmware can binary-search by char.
        let mut chars: Vec<char> = spec.charset.chars().collect();
        chars.sort_unstable();
        chars.dedup();

        for ch in chars {
            let (metrics, coverage) = face.rasterize(ch, spec.px);
            let offset = bitmap.len();
            bitmap.extend_from_slice(&coverage);
            // fontdue gives ymin as the baseline-relative bottom edge, positive
            // upward. The blitter wants a downward top edge, so flip it here
            // rather than in the hot path.
            let top = -(metrics.ymin + metrics.height as i32);
            writeln!(
                generated_entry(&mut entries),
                "    Glyph {{ ch: '{}', w: {}, h: {}, left: {}, top: {}, advance: {}, offset: {} }},",
                escape(ch),
                metrics.width,
                metrics.height,
                metrics.xmin,
                top,
                metrics.advance_width.round() as i32,
                offset,
            )
            .unwrap();
            count += 1;
        }

        let bin_name = format!("font_{}.bin", spec.ident.to_lowercase());
        fs::write(out_dir.join(&bin_name), &bitmap).unwrap();

        let line_metrics = face
            .horizontal_line_metrics(spec.px)
            .expect("font has no horizontal line metrics");

        writeln!(
            generated,
            "pub static {ident}: Font = Font {{\n    \
                 glyphs: &[\n{entries}    ],\n    \
                 coverage: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{bin}\")),\n    \
                 ascent: {ascent},\n    \
                 px: {px},\n}};\n",
            ident = spec.ident,
            entries = entries,
            bin = bin_name,
            ascent = line_metrics.ascent.round() as i32,
            px = spec.px.round() as i32,
        )
        .unwrap();

        println!(
            "cargo:warning={} px={} glyphs={} coverage={} KiB",
            spec.ident,
            spec.px,
            count,
            bitmap.len() / 1024
        );
    }

    // Navigation icons come from one professionally drawn typeface so the
    // borderless settings button and circled back button share weight/style.
    let icon_path = assets.join("Font-Awesome-7-Free-Solid-900.otf");
    println!("cargo:rerun-if-changed={}", icon_path.display());
    let icon_data = fs::read(&icon_path).unwrap();
    let icon_face = fontdue::Font::from_bytes(icon_data, fontdue::FontSettings::default()).unwrap();
    let mut icon_bitmap = Vec::new();
    let mut icon_entries = String::new();
    // gear, arrow-up (keyboard shift), angle-left/right, delete-left
    // (backspace). Kept in codepoint order: `Font::glyph` binary-searches this
    // table, so an out-of-order entry would simply not be found.
    for ch in ['\u{f013}', '\u{f062}', '\u{f104}', '\u{f105}', '\u{f55a}']
        .into_iter()
        .collect::<std::collections::BTreeSet<_>>()
    {
        let (metrics, coverage) = icon_face.rasterize(ch, 42.0);
        // A codepoint this typeface does not carry rasterizes to nothing, and
        // would then ship as an invisible button. Fail the build instead.
        assert!(
            metrics.width > 0 && metrics.height > 0,
            "icon U+{:04X} is missing from the icon font",
            ch as u32
        );
        let offset = icon_bitmap.len();
        icon_bitmap.extend_from_slice(&coverage);
        let top = -(metrics.ymin + metrics.height as i32);
        writeln!(
            generated_entry(&mut icon_entries),
            "    Glyph {{ ch: '{}', w: {}, h: {}, left: {}, top: {}, advance: {}, offset: {} }},",
            escape(ch),
            metrics.width,
            metrics.height,
            metrics.xmin,
            top,
            metrics.advance_width.round() as i32,
            offset,
        )
        .unwrap();
    }
    fs::write(out_dir.join("font_icon.bin"), &icon_bitmap).unwrap();
    writeln!(generated,
        "pub static ICON: Font = Font {{\n    glyphs: &[\n{icon_entries}    ],\n    coverage: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/font_icon.bin\")),\n    ascent: 42,\n    px: 42,\n}};\n"
    ).unwrap();

    fs::write(out_dir.join("fonts.rs"), generated).unwrap();
    emit_secrets(&manifest, &out_dir);
}

/// Bakes Wi-Fi and controller credentials in from a gitignored `wifi.txt`, or
/// from the environment when one is set (handy for CI, and for building without
/// the file present at all).
///
/// Keeping them out of tracked source is the whole point: the repository is
/// public, and a Wi-Fi PSK plus an Axis admin password is exactly the pair you
/// do not want in a commit.
fn emit_secrets(manifest: &Path, out_dir: &Path) {
    let path = manifest.join("wifi.txt");
    println!("cargo:rerun-if-changed={}", path.display());
    for key in ["WIFI_SSID", "WIFI_PASS", "RB_HOST", "RB_USER", "RB_PASS"] {
        println!("cargo:rerun-if-env-changed={key}");
    }

    let text = fs::read_to_string(&path).unwrap_or_default();
    let from_file = |name: &str| -> Option<String> {
        text.lines()
            .map(str::trim)
            .filter(|l| !l.starts_with('#'))
            .find_map(|l| l.strip_prefix(name)?.strip_prefix('=').map(str::to_string))
    };
    let pick = |env_key: &str, file_key: &str, default: &str| -> String {
        std::env::var(env_key)
            .ok()
            .or_else(|| from_file(file_key))
            .unwrap_or_else(|| default.to_string())
    };

    let ssid = pick("WIFI_SSID", "ssid", "");
    let pass = pick("WIFI_PASS", "pass", "");
    let host = pick("RB_HOST", "host", "192.168.4.200");
    let user = pick("RB_USER", "user", "root");
    let api_pass = pick("RB_PASS", "apipass", "");

    if ssid.is_empty() {
        println!(
            "cargo:warning=no Wi-Fi SSID configured (create wifi.txt or set WIFI_SSID); \
             the panel will run on bench data only"
        );
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs from wifi.txt - do not edit, do not commit.\n");
    writeln!(out, "pub const WIFI_SSID: &str = {ssid:?};").unwrap();
    writeln!(out, "pub const WIFI_PASS: &str = {pass:?};").unwrap();
    writeln!(out, "pub const RB_HOST: &str = {host:?};").unwrap();
    writeln!(out, "pub const RB_USER: &str = {user:?};").unwrap();
    writeln!(out, "pub const RB_PASS: &str = {api_pass:?};").unwrap();
    fs::write(out_dir.join("secrets.rs"), out).unwrap();
}

// Tiny shim so the writeln! above can borrow the entries buffer inline.
fn generated_entry(s: &mut String) -> &mut String {
    s
}

fn escape(ch: char) -> String {
    match ch {
        '\'' => "\\'".to_string(),
        '\\' => "\\\\".to_string(),
        c => c.to_string(),
    }
}
